services:
  web:
    image: nginx:alpine
    container_name: p41_web
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt:ro
      - ./certs/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key:ro
    depends_on:
      - sftp

  sftp:
    image: atmoz/sftp:alpine
    container_name: p41_sftp
    ports:
      - '2222:22'
    command: 'daw:1234:1001:1001:upload'
    volumes:
      - ./www:/home/daw/upload