services:
  web:
    image: nginx:alpine
    container_name: p41_web
    ports:
      - "8080:80"
    volumes:
      - ./www:/usr/share/nginx/html:ro
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - sftp

  sftp:
    image: atmoz/sftp:alpine
    container_name: p41_sftp
    ports:
      - "2222:22"
    # usuario:pass:uid:gid:directorio
    command: "daw:1234:1001:1001:upload"
    volumes:
      # El contenedor SFTP escribe en /home/daw/upload
      - ./www:/home/daw/upload
